#! /bin/zsh
# Clone a git repositary, storing a local tarball of the repositary.

# This is where I store files to be archived, the name is just a throwback to
# the olde world.
ARCHIVE_DIR=/mnt/cdrom_pending/git-packages

url=$1
proj=${${2:-${1##*/}}/%.git}
if [ -z "${url}" ]
then
    echo "clonegit <url> [proj]"
    exit 1
fi
git clone --no-checkout ${url} ${proj} || exit 1
[ ! -d ${ARCHIVE_DIR} ] && mkdir ${ARCHIVE_DIR}
tar --create --bzip2 --file=${ARCHIVE_DIR}/${proj}-$(date -I).git.tar ${proj}
cd ${proj}
git checkout
