#! /bin/sh
# Open file in current gvim session, if one exists.

if [ "$1" == "-k" ]
then
    server=$2
    shift 2
else
    server="$(gvim --serverlist | head -1)"
fi

gvim --servername ${server:-GVIM} ${server:+--remote-silent}  $@
