#! /bin/sh
# Simple way to open whatever is in the current selection

source $(dirname $(readlink -f ${0}))/tool_settings.sh

link=$(xsel)
if [ -z "${link}" ]
then
    dzen_text <<< "No text in selection"
else
    dzen_text <<< "Opening link from selection - ${link}"
    xdg-open "${link}"
fi
