#! /bin/sh
# Fire up an application, and show a popup notification.  This is mainly used
# for wrapping commands started with keybindings that take some time to show
# activity.

source $(dirname $(readlink -f ${0}))/tool_settings.sh

[ -z "$1" ] && exit 1
app=$1
shift
dzen_text <<< "${NAME:-${app##*/}} starting" &
exec ${app} $@
