#! /bin/zsh
# I keep a list of pages I want to read/files I want to fetch *at some point* in
# ~/urls and ~/downloads respectively, this script just adds another entry to
# it.

source $(dirname $(readlink -f ${0}))/tool_settings.sh

[ -z "$1" ] && url=$(xsel) || url=$1
[ -z "${url}" ] && exit 1
ftype=${${0:t}%_*}s
echo "${url}" >> ~/${ftype}
dzen_text <<< "${url} added to ${ftype}"
